### PR TITLE
Refactor sigmaclip to use spectral-cube

### PR DESCRIPTION
**Pull request by keflavich**
This implements `c_sigmaclip_scube` as a possible replacement to `c_sigmaclip`, since spectral-cube can handle parallelization via dask.

### CODE REVIEW

**Comment by keflavich** [comment]
@astrofrog I could use advice on the use of dask-related tools here.  I suspect this is actually using them _very_ inefficiently right now; it appears that these two lines:
https://github.com/radio-astro-tools/statcont/blob/f12fec52192a7eb45fe2e9aa7d7bc8ea1f6f8273/statcont/cont_finding.py#L560-L567
involve re-running `sigma_clip` twice.  Is that right?  What's the best way to avoid that?  Write intermediate (filtered) to disk?

**Comment by keflavich** [comment]
The related question for spectral-cube is: how do we document this appropriately to prevent users from making my mistakes?

**Comment by astrofrog** [comment]
When calling ``sigma_clip_spectrally``, you should indeed call ``save_to_tmp_dir`` to avoid calling it twice

**Comment by keflavich** [comment]
I quoted the wrong lines, they're supposed to be these:
https://github.com/keflavich/statcont/blob/refactor_sigmaclip/statcont/cont_finding.py#L572-L579
notably, the `include()` is what's being summed over

**Pull request merged**
